---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: splunk-cisco-app-navigator
    title: Splunk Cisco App Navigator
    functionalDomain: []
    description: ' Splunk Cisco App Navigator provides a unified glass-pane for discovering, deploying, and managing the full portfolio of Cisco Splunk apps and add-ons. Browse the product catalog, check installation health, view documentation, and streamline onboarding across Splunk Enterprise and Splunk Cloud — all from a single dashboard.'
    annotations:
        backstage.io/source-location: url:https://cd.splunkdev.com/sg-cloud-tools-engineering/splunk-cisco-app-navigator
        splunk.com/issue-tracker-url: http://go/replace/me
        splunk.com/slack-url: http://go/replace/me
        backstage.io/view-url: https://cd.splunkdev.com/sg-cloud-tools-engineering/splunk-cisco-app-navigator/-/blob/main/.service-manifests/splunk-cisco-app-navigator-component.yaml
        backstage.io/edit-url: https://cd.splunkdev.com/sg-cloud-tools-engineering/splunk-cisco-app-navigator/-/edit/main/.service-manifests/splunk-cisco-app-navigator-component.yaml
    links:
        - title: Overview
          url: http://go/replace/me
        - title: ERD/RFC
          url: http://go/replace/me
        - title: Ops Runbook
          url: http://go/replace/me
spec:
    lifecycle: production
    type: product
    owner: group:sg-cloud-sales-tools-engineering
