
[install]
state = enabled
build = cbfa0446

[id]
name = splunk-cisco-app-navigator
version = 1.0.22

[launcher]
author = Amir (AK) Khamis & Alec Chamberlain
description = Splunk Cisco App Navigator provides a unified glass-pane for discovering, deploying, and managing the full portfolio of Cisco Splunk apps and add-ons. Browse the product catalog, check installation health, view documentation, and streamline onboarding across Splunk Enterprise and Splunk Cloud — all from a single dashboard.
version = 1.0.22

[package]
check_for_updates = 1
id = splunk-cisco-app-navigator

[ui]
label = Splunk Cisco App Navigator
is_visible = 1
show_in_nav = 1
supported_themes = light,dark


[triggers]
reload.products = simple
reload.splunk_create = simple
