[id]
name = splunk-cisco-app-navigator
version = 1.0.2

[ui]
is_visible = 1
label = Splunk Cisco App Navigator
supported_themes = light,dark
show_in_nav = 1

[launcher]
author = Splunk
description = Splunk Cisco App Navigator provides a unified glass-pane for discovering, deploying, and managing the full portfolio of Cisco Splunk apps and add-ons. Browse the product catalog, check installation health, view documentation, and streamline onboarding across Splunk Enterprise and Splunk Cloud — all from a single dashboard.
version = 1.0.2

[package]
check_for_updates = 1
id = splunk-cisco-app-navigator

[install]
# is_configured = 1
build = 1
state = enabled

[triggers]
reload.products = simple
reload.splunk_create = simple
