# commands.conf — Custom search commands for Splunk Cisco App Navigator
# Docs: https://docs.splunk.com/Documentation/Splunk/latest/Admin/Commandsconf

[synclookup]
enableheader = true
filename = synclookup.py
generating = true
outputheader = true
python.version = python3
requires_srinfo = true
retainsevents = true
streaming = false
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true

[synccatalog]
enableheader = true
filename = synccatalog.py
generating = true
outputheader = true
python.version = python3
requires_srinfo = true
retainsevents = true
streaming = false
supports_getinfo = true
supports_multivalues = true
supports_rawargs = true
