#!/usr/bin/env bash
# Hide apps from Splunk nav by creating local/app.conf with show_in_nav = 0
set -e

APPS_DIR="/opt/splunk/etc/apps"
APPS=(
"Alef_TA_MIMEDecoder"
"CMX"
"Cisco-suite-for-splunk"
"CiscoNVM"
"Cisco_Bug_Search_and_Analytics"
"Cisco_CWS_TA"
"Cisco_DP_PD"
"Cisco_WSA_Insight"
"DA-ITSI-CP-CUST-ATLAS-CISCO-DNA"
"DA-ITSI-CP-CUST-ATLAS-CISCO-WSA"
"SA-openVulnQuery"
"SA_cisco_cdr_axl"
"SA_cisco_meeting_server"
"SA_oracle_sbc_cdr"
"SA_sideview_webex"
"SA_teams_json"
"Splunk-TA-cisco-catalyst-center"
"Splunk-TA-cisco-dnacenter"
"Splunk-cisco-catalyst-center"
"Splunk_CiscoDNACenter"
"Splunk_CiscoISE"
"Splunk_CiscoSecuritySuite"
"Splunk_MCP_Server"
"Splunk_TA_AppDynamics"
"Splunk_TA_CCX_Cisco_ISE"
"Splunk_TA_CCX_Cisco_Meraki"
"Splunk_TA_CCX_Cisco_Secure_Endpoint"
"Splunk_TA_CCX_Cisco_Secure_Network_Analytics"
"Splunk_TA_CCX_DUO_Connector_Support"
"Splunk_TA_CCX_Unified_Cisco_Firepower_eStreamer"
"Splunk_TA_Cisco_Intersight"
"Splunk_TA_Talos_Intelligence"
"Splunk_TA_cisco-asa"
"Splunk_TA_cisco-esa"
"Splunk_TA_cisco-estreamer_Enosys"
"Splunk_TA_cisco-ips"
"Splunk_TA_cisco-ise"
"Splunk_TA_cisco-ucs"
"Splunk_TA_cisco-wsa"
"Splunk_TA_cisco_meraki"
"Splunk_TA_sourcefire"
"Splunk_TA_stream"
"TA-CMX"
"TA-Cisco-NVM"
"TA-DP-webex-teams"
"TA-DUOSecurity2FA"
"TA-Umbrella"
"TA-add-on-for-cisco-prime-infrastructure"
"TA-cisco-amp4e"
"TA-cisco-cloud-security-addon"
"TA-cisco-cloud-security-umbrella-addon"
"TA-cisco-etd-connector"
"TA-cisco-firepower-pcap-add-on"
"TA-cisco-firepower-threat-defense-ftd-dashboards"
"TA-cisco-firepower-threat-defense-ftd-sourcetype"
"TA-cisco-secure-malware-analytics"
"TA-cisco-stealthwatch"
"TA-cisco-threat-grid"
"TA-cisco-threat-response"
"TA-cisco_DP_PD"
"TA-cisco_acs"
"TA-cisco_cybervision"
"TA-cisco_ios"
"TA-cisco_meraki_operations"
"TA-cisco_umbrella"
"TA-ciscoaxl"
"TA-eStreamer"
"TA-intersight-addon"
"TA-lcs-plug-in"
"TA-stealthwatch_dataexporter"
"TA-vscode_audit"
"TA_Meraki_SNMP_trap"
"TA_cisco-ACI"
"TA_cisco-NI"
"TA_cisco-Nexus-9k"
"TA_cisco-candid"
"TA_cisco_catalyst"
"TA_cisco_cdr"
"TA_oracle_sbc_cdr"
"WebexTeams_AlertAction"
"amp4e_events_input"
"appdynamics"
"botsv3_data_set"
"canary"
"chargeback_app_splunk_cloud"
"cisco-app-ACI"
"cisco-app-NI"
"cisco-app-Nexus-9k"
"cisco-app-candid"
"cisco-catalyst-app"
"cisco-cloud-security"
"cisco-sdwan-app"
"cisco_cdr"
"cisco_cybervision_app_for_splunk"
"cisco_dc_networking_app_for_splunk"
"cisco_ios"
"cisco_sna_app"
"cisco_thousandeyes_alerting_app_for_splunk"
"cisco_webex_meetings_app_for_splunk"
"cloudlock"
"demo_addon_for_splunk"
"duo_splunkapp"
"eStreamer"
"eStreamer-Dashboard"
"field-solutions-demo-data-gen"
"firegen_cisco_asa"
"firepower_dashboard"
"insights_app_splunk"
"is4s_internal"
"lcs_insights"
"lookup_editor"
"meraki_ta"
"my-todo-app"
"opendns_investigate"
"relay-module"
"splunk_app_AppDynamics"
"splunk_app_spark_room"
"splunk_app_stream"
"splunk_app_stream_ipfix_cisco_hsl"
"splunk_cisco_ise_alert"
"splunk_ingest_actions"
"splunk_spark_app"
"ta-cisco-sdwan"
"ta-cisco-webex-meetings-add-on-for-splunk"
"ta_cisco_spaces"
"ta_cisco_thousandeyes"
"ta_cisco_webex_add_on_for_splunk"
"ti-cisco-vuln"
"tr-splunk-relay"
"webex_alert"
)

hidden=0
skipped=0
already=0

for app in "${APPS[@]}"; do
    app_dir="$APPS_DIR/$app"
    if [[ ! -d "$app_dir" ]]; then
        ((skipped++))
        continue
    fi
    local_dir="$app_dir/local"
    conf="$local_dir/app.conf"
    # Check if already hidden
    if [[ -f "$conf" ]] && grep -q 'show_in_nav.*=.*0' "$conf" 2>/dev/null; then
        ((already++))
        continue
    fi
    mkdir -p "$local_dir"
    if [[ -f "$conf" ]]; then
        if grep -q '^\[ui\]' "$conf" 2>/dev/null; then
            # [ui] exists — add show_in_nav after it
            sed -i '' '/^\[ui\]/a\'$'\n''show_in_nav = 0' "$conf"
        else
            printf '\n[ui]\nshow_in_nav = 0\n' >> "$conf"
        fi
    else
        printf '[ui]\nshow_in_nav = 0\n' > "$conf"
    fi
    echo "  Hidden: $app"
    ((hidden++))
done

echo ""
echo "Done: $hidden hidden, $already already hidden, $skipped not found"
